//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowClientSide.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name projectName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDataInProjectTable", ReplyAction="*")]
        WindowClientSide.ServiceReference1.AddDataInProjectTableResponse AddDataInProjectTable(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDataInProjectTable", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInProjectTableResponse> AddDataInProjectTableAsync(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllProjectsByNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProjectsByName", ReplyAction="*")]
        WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse GetAllProjectsByName(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProjectsByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse> GetAllProjectsByNameAsync(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInProjectTableById", ReplyAction="*")]
        void DeleteDataInProjectTableById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInProjectTableById", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteDataInProjectTableByIdAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataInProjectTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataInProjectTable", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody Body;
        
        public AddDataInProjectTableRequest() {
        }
        
        public AddDataInProjectTableRequest(WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDataInProjectTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectName;
        
        public AddDataInProjectTableRequestBody() {
        }
        
        public AddDataInProjectTableRequestBody(int id, string projectName) {
            this.id = id;
            this.projectName = projectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataInProjectTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataInProjectTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.AddDataInProjectTableResponseBody Body;
        
        public AddDataInProjectTableResponse() {
        }
        
        public AddDataInProjectTableResponse(WindowClientSide.ServiceReference1.AddDataInProjectTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDataInProjectTableResponseBody {
        
        public AddDataInProjectTableResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProjectsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProjectsByName", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody Body;
        
        public GetAllProjectsByNameRequest() {
        }
        
        public GetAllProjectsByNameRequest(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProjectsByNameRequestBody {
        
        public GetAllProjectsByNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProjectsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProjectsByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.GetAllProjectsByNameResponseBody Body;
        
        public GetAllProjectsByNameResponse() {
        }
        
        public GetAllProjectsByNameResponse(WindowClientSide.ServiceReference1.GetAllProjectsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProjectsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowClientSide.ServiceReference1.ArrayOfString GetAllProjectsByNameResult;
        
        public GetAllProjectsByNameResponseBody() {
        }
        
        public GetAllProjectsByNameResponseBody(WindowClientSide.ServiceReference1.ArrayOfString GetAllProjectsByNameResult) {
            this.GetAllProjectsByNameResult = GetAllProjectsByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowClientSide.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowClientSide.ServiceReference1.WebService1Soap>, WindowClientSide.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.AddDataInProjectTableResponse WindowClientSide.ServiceReference1.WebService1Soap.AddDataInProjectTable(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request) {
            return base.Channel.AddDataInProjectTable(request);
        }
        
        public void AddDataInProjectTable(int id, string projectName) {
            WindowClientSide.ServiceReference1.AddDataInProjectTableRequest inValue = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody();
            inValue.Body.id = id;
            inValue.Body.projectName = projectName;
            WindowClientSide.ServiceReference1.AddDataInProjectTableResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).AddDataInProjectTable(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInProjectTableResponse> WindowClientSide.ServiceReference1.WebService1Soap.AddDataInProjectTableAsync(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request) {
            return base.Channel.AddDataInProjectTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInProjectTableResponse> AddDataInProjectTableAsync(int id, string projectName) {
            WindowClientSide.ServiceReference1.AddDataInProjectTableRequest inValue = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody();
            inValue.Body.id = id;
            inValue.Body.projectName = projectName;
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).AddDataInProjectTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse WindowClientSide.ServiceReference1.WebService1Soap.GetAllProjectsByName(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request) {
            return base.Channel.GetAllProjectsByName(request);
        }
        
        public WindowClientSide.ServiceReference1.ArrayOfString GetAllProjectsByName() {
            WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest inValue = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody();
            WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).GetAllProjectsByName(inValue);
            return retVal.Body.GetAllProjectsByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse> WindowClientSide.ServiceReference1.WebService1Soap.GetAllProjectsByNameAsync(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request) {
            return base.Channel.GetAllProjectsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse> GetAllProjectsByNameAsync() {
            WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest inValue = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody();
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).GetAllProjectsByNameAsync(inValue);
        }
        
        public void DeleteDataInProjectTableById(int id) {
            base.Channel.DeleteDataInProjectTableById(id);
        }
        
        public System.Threading.Tasks.Task DeleteDataInProjectTableByIdAsync(int id) {
            return base.Channel.DeleteDataInProjectTableByIdAsync(id);
        }
    }
}
