//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowClientSide.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name projectName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDataInProjectTable", ReplyAction="*")]
        WindowClientSide.ServiceReference1.AddDataInProjectTableResponse AddDataInProjectTable(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDataInProjectTable", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInProjectTableResponse> AddDataInProjectTableAsync(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllProjectsByNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProjectsByName", ReplyAction="*")]
        WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse GetAllProjectsByName(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProjectsByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse> GetAllProjectsByNameAsync(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInProjectTableById", ReplyAction="*")]
        void DeleteDataInProjectTableById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInProjectTableById", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteDataInProjectTableByIdAsync(int id);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInProjectTableByName", ReplyAction="*")]
        WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponse DeleteDataInProjectTableByName(WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInProjectTableByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponse> DeleteDataInProjectTableByNameAsync(WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest request);
        
        // CODEGEN: Generating message contract since element name sprintName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDataInSprinTable", ReplyAction="*")]
        WindowClientSide.ServiceReference1.AddDataInSprinTableResponse AddDataInSprinTable(WindowClientSide.ServiceReference1.AddDataInSprinTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDataInSprinTable", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInSprinTableResponse> AddDataInSprinTableAsync(WindowClientSide.ServiceReference1.AddDataInSprinTableRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSprintsByNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSprintsByName", ReplyAction="*")]
        WindowClientSide.ServiceReference1.GetAllSprintsByNameResponse GetAllSprintsByName(WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSprintsByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllSprintsByNameResponse> GetAllSprintsByNameAsync(WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInSprintTableByName", ReplyAction="*")]
        WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponse DeleteDataInSprintTableByName(WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDataInSprintTableByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponse> DeleteDataInSprintTableByNameAsync(WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataInProjectTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataInProjectTable", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody Body;
        
        public AddDataInProjectTableRequest() {
        }
        
        public AddDataInProjectTableRequest(WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDataInProjectTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectName;
        
        public AddDataInProjectTableRequestBody() {
        }
        
        public AddDataInProjectTableRequestBody(int id, string projectName) {
            this.id = id;
            this.projectName = projectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataInProjectTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataInProjectTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.AddDataInProjectTableResponseBody Body;
        
        public AddDataInProjectTableResponse() {
        }
        
        public AddDataInProjectTableResponse(WindowClientSide.ServiceReference1.AddDataInProjectTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDataInProjectTableResponseBody {
        
        public AddDataInProjectTableResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProjectsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProjectsByName", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody Body;
        
        public GetAllProjectsByNameRequest() {
        }
        
        public GetAllProjectsByNameRequest(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProjectsByNameRequestBody {
        
        public GetAllProjectsByNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProjectsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProjectsByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.GetAllProjectsByNameResponseBody Body;
        
        public GetAllProjectsByNameResponse() {
        }
        
        public GetAllProjectsByNameResponse(WindowClientSide.ServiceReference1.GetAllProjectsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProjectsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowClientSide.ServiceReference1.ArrayOfString GetAllProjectsByNameResult;
        
        public GetAllProjectsByNameResponseBody() {
        }
        
        public GetAllProjectsByNameResponseBody(WindowClientSide.ServiceReference1.ArrayOfString GetAllProjectsByNameResult) {
            this.GetAllProjectsByNameResult = GetAllProjectsByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataInProjectTableByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataInProjectTableByName", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequestBody Body;
        
        public DeleteDataInProjectTableByNameRequest() {
        }
        
        public DeleteDataInProjectTableByNameRequest(WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataInProjectTableByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public DeleteDataInProjectTableByNameRequestBody() {
        }
        
        public DeleteDataInProjectTableByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataInProjectTableByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataInProjectTableByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponseBody Body;
        
        public DeleteDataInProjectTableByNameResponse() {
        }
        
        public DeleteDataInProjectTableByNameResponse(WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteDataInProjectTableByNameResponseBody {
        
        public DeleteDataInProjectTableByNameResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataInSprinTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataInSprinTable", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.AddDataInSprinTableRequestBody Body;
        
        public AddDataInSprinTableRequest() {
        }
        
        public AddDataInSprinTableRequest(WindowClientSide.ServiceReference1.AddDataInSprinTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDataInSprinTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sprintName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sprintPeriod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string productIncrementVersion;
        
        public AddDataInSprinTableRequestBody() {
        }
        
        public AddDataInSprinTableRequestBody(int id, string sprintName, string sprintPeriod, string productIncrementVersion) {
            this.id = id;
            this.sprintName = sprintName;
            this.sprintPeriod = sprintPeriod;
            this.productIncrementVersion = productIncrementVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataInSprinTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataInSprinTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.AddDataInSprinTableResponseBody Body;
        
        public AddDataInSprinTableResponse() {
        }
        
        public AddDataInSprinTableResponse(WindowClientSide.ServiceReference1.AddDataInSprinTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDataInSprinTableResponseBody {
        
        public AddDataInSprinTableResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSprintsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSprintsByName", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.GetAllSprintsByNameRequestBody Body;
        
        public GetAllSprintsByNameRequest() {
        }
        
        public GetAllSprintsByNameRequest(WindowClientSide.ServiceReference1.GetAllSprintsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSprintsByNameRequestBody {
        
        public GetAllSprintsByNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSprintsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSprintsByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.GetAllSprintsByNameResponseBody Body;
        
        public GetAllSprintsByNameResponse() {
        }
        
        public GetAllSprintsByNameResponse(WindowClientSide.ServiceReference1.GetAllSprintsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSprintsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowClientSide.ServiceReference1.ArrayOfString GetAllSprintsByNameResult;
        
        public GetAllSprintsByNameResponseBody() {
        }
        
        public GetAllSprintsByNameResponseBody(WindowClientSide.ServiceReference1.ArrayOfString GetAllSprintsByNameResult) {
            this.GetAllSprintsByNameResult = GetAllSprintsByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataInSprintTableByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataInSprintTableByName", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequestBody Body;
        
        public DeleteDataInSprintTableByNameRequest() {
        }
        
        public DeleteDataInSprintTableByNameRequest(WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataInSprintTableByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public DeleteDataInSprintTableByNameRequestBody() {
        }
        
        public DeleteDataInSprintTableByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataInSprintTableByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataInSprintTableByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponseBody Body;
        
        public DeleteDataInSprintTableByNameResponse() {
        }
        
        public DeleteDataInSprintTableByNameResponse(WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteDataInSprintTableByNameResponseBody {
        
        public DeleteDataInSprintTableByNameResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowClientSide.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowClientSide.ServiceReference1.WebService1Soap>, WindowClientSide.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.AddDataInProjectTableResponse WindowClientSide.ServiceReference1.WebService1Soap.AddDataInProjectTable(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request) {
            return base.Channel.AddDataInProjectTable(request);
        }
        
        public void AddDataInProjectTable(int id, string projectName) {
            WindowClientSide.ServiceReference1.AddDataInProjectTableRequest inValue = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody();
            inValue.Body.id = id;
            inValue.Body.projectName = projectName;
            WindowClientSide.ServiceReference1.AddDataInProjectTableResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).AddDataInProjectTable(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInProjectTableResponse> WindowClientSide.ServiceReference1.WebService1Soap.AddDataInProjectTableAsync(WindowClientSide.ServiceReference1.AddDataInProjectTableRequest request) {
            return base.Channel.AddDataInProjectTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInProjectTableResponse> AddDataInProjectTableAsync(int id, string projectName) {
            WindowClientSide.ServiceReference1.AddDataInProjectTableRequest inValue = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.AddDataInProjectTableRequestBody();
            inValue.Body.id = id;
            inValue.Body.projectName = projectName;
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).AddDataInProjectTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse WindowClientSide.ServiceReference1.WebService1Soap.GetAllProjectsByName(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request) {
            return base.Channel.GetAllProjectsByName(request);
        }
        
        public WindowClientSide.ServiceReference1.ArrayOfString GetAllProjectsByName() {
            WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest inValue = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody();
            WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).GetAllProjectsByName(inValue);
            return retVal.Body.GetAllProjectsByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse> WindowClientSide.ServiceReference1.WebService1Soap.GetAllProjectsByNameAsync(WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest request) {
            return base.Channel.GetAllProjectsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllProjectsByNameResponse> GetAllProjectsByNameAsync() {
            WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest inValue = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.GetAllProjectsByNameRequestBody();
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).GetAllProjectsByNameAsync(inValue);
        }
        
        public void DeleteDataInProjectTableById(int id) {
            base.Channel.DeleteDataInProjectTableById(id);
        }
        
        public System.Threading.Tasks.Task DeleteDataInProjectTableByIdAsync(int id) {
            return base.Channel.DeleteDataInProjectTableByIdAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponse WindowClientSide.ServiceReference1.WebService1Soap.DeleteDataInProjectTableByName(WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest request) {
            return base.Channel.DeleteDataInProjectTableByName(request);
        }
        
        public void DeleteDataInProjectTableByName(string name) {
            WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest inValue = new WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequestBody();
            inValue.Body.name = name;
            WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).DeleteDataInProjectTableByName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponse> WindowClientSide.ServiceReference1.WebService1Soap.DeleteDataInProjectTableByNameAsync(WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest request) {
            return base.Channel.DeleteDataInProjectTableByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameResponse> DeleteDataInProjectTableByNameAsync(string name) {
            WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest inValue = new WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.DeleteDataInProjectTableByNameRequestBody();
            inValue.Body.name = name;
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).DeleteDataInProjectTableByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.AddDataInSprinTableResponse WindowClientSide.ServiceReference1.WebService1Soap.AddDataInSprinTable(WindowClientSide.ServiceReference1.AddDataInSprinTableRequest request) {
            return base.Channel.AddDataInSprinTable(request);
        }
        
        public void AddDataInSprinTable(int id, string sprintName, string sprintPeriod, string productIncrementVersion) {
            WindowClientSide.ServiceReference1.AddDataInSprinTableRequest inValue = new WindowClientSide.ServiceReference1.AddDataInSprinTableRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.AddDataInSprinTableRequestBody();
            inValue.Body.id = id;
            inValue.Body.sprintName = sprintName;
            inValue.Body.sprintPeriod = sprintPeriod;
            inValue.Body.productIncrementVersion = productIncrementVersion;
            WindowClientSide.ServiceReference1.AddDataInSprinTableResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).AddDataInSprinTable(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInSprinTableResponse> WindowClientSide.ServiceReference1.WebService1Soap.AddDataInSprinTableAsync(WindowClientSide.ServiceReference1.AddDataInSprinTableRequest request) {
            return base.Channel.AddDataInSprinTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.AddDataInSprinTableResponse> AddDataInSprinTableAsync(int id, string sprintName, string sprintPeriod, string productIncrementVersion) {
            WindowClientSide.ServiceReference1.AddDataInSprinTableRequest inValue = new WindowClientSide.ServiceReference1.AddDataInSprinTableRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.AddDataInSprinTableRequestBody();
            inValue.Body.id = id;
            inValue.Body.sprintName = sprintName;
            inValue.Body.sprintPeriod = sprintPeriod;
            inValue.Body.productIncrementVersion = productIncrementVersion;
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).AddDataInSprinTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.GetAllSprintsByNameResponse WindowClientSide.ServiceReference1.WebService1Soap.GetAllSprintsByName(WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest request) {
            return base.Channel.GetAllSprintsByName(request);
        }
        
        public WindowClientSide.ServiceReference1.ArrayOfString GetAllSprintsByName() {
            WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest inValue = new WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.GetAllSprintsByNameRequestBody();
            WindowClientSide.ServiceReference1.GetAllSprintsByNameResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).GetAllSprintsByName(inValue);
            return retVal.Body.GetAllSprintsByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllSprintsByNameResponse> WindowClientSide.ServiceReference1.WebService1Soap.GetAllSprintsByNameAsync(WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest request) {
            return base.Channel.GetAllSprintsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.GetAllSprintsByNameResponse> GetAllSprintsByNameAsync() {
            WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest inValue = new WindowClientSide.ServiceReference1.GetAllSprintsByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.GetAllSprintsByNameRequestBody();
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).GetAllSprintsByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponse WindowClientSide.ServiceReference1.WebService1Soap.DeleteDataInSprintTableByName(WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest request) {
            return base.Channel.DeleteDataInSprintTableByName(request);
        }
        
        public void DeleteDataInSprintTableByName(string name) {
            WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest inValue = new WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequestBody();
            inValue.Body.name = name;
            WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponse retVal = ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).DeleteDataInSprintTableByName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponse> WindowClientSide.ServiceReference1.WebService1Soap.DeleteDataInSprintTableByNameAsync(WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest request) {
            return base.Channel.DeleteDataInSprintTableByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameResponse> DeleteDataInSprintTableByNameAsync(string name) {
            WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest inValue = new WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequest();
            inValue.Body = new WindowClientSide.ServiceReference1.DeleteDataInSprintTableByNameRequestBody();
            inValue.Body.name = name;
            return ((WindowClientSide.ServiceReference1.WebService1Soap)(this)).DeleteDataInSprintTableByNameAsync(inValue);
        }
    }
}
